### ISSUE TITLE
[question] General idea of using phoenix

### ISSUE THREAD

**Issue by Elgcahlxukuth** [GothicKit/phoenix-java-interface#1]
Hi,
I finally managed to take a closer look into the interface.
(Turned out the GraalVM is too bugged to just execute LLVM files compiled out of C++ sources, as it is supposed to, so I will probably go with JNI approach for now)
I appreciate your effort to make phoenix available in many ways ;) Thank you.

Let's say I want to create some kind of reimplementation of Gothic game.
As I understand, I can use your virtual machine to execute compiled gothic scripts (`GOTHIC.DAT`) and that should fill my game world with all the content like NPCs and items. This can probably be achieved with:
`PxDaedalusScript pxScriptLoad(PxBuffer buffer);`
In order for the virtual machine to actually have any effect on my game, I need to bind all Dedalus commands (those: https://github.com/GothicII/EnglishCleanedScripts/blob/master/Content/AI/AI_Intern/Externals.d) to my own Java methods, using this:
`void pxVmRegisterExternal(PxVm vm, String name, PxVmExternalCallback cb);`
so that any time Dedalus tries to do something in the game, my binded Java methods will reflect those actions in the game mechanics.
Is my understanding correct so far?

I have a question regarding the VM itself. Is it stateless in terms of game world content? The way I see it, any change to NPC/Item made by Dedalus have to be reflected in the state of my own Java objects and that is the only place where the modified state is stored. VM does not store any global data, like current state of the Hero, quests, etc. Right?

Cheers

**Comment by lmichaelis** [comment]
Hi @Elgcahlxukuth,

> Is my understanding correct so far?

Yes that is correct, though you would use `pxVmLoad` instead of `pxScriptLoad`.

> VM does not store any global data, like current state of the Hero, quests, etc. Right?

It does generally store _some_ global state but none of that is instance-related or required to be known by your code unless you need to implement save-states. Everything else regarding instances (like NPCs, Items, Spells and so on) is stored within `PxInstance`s which you have to keep track of.

Here's an example of global Daedalus state:
```
Index    Flags   Parent                    Address  R Name
00005e0e i       *UND*                     ffffffff   WOLF_ARMOR_DAY
00005e17 i       *UND*                     ffffffff   DIA_WOLF_BENGAR_ONETIME
00005e18 i       *UND*                     ffffffff   WOLF_BENGAR_GELD
00005e1e i       *UND*                     ffffffff   DIA_WOLF_PERMKAP3_ONETIME
00005e26 i       *UND*                     ffffffff   WOLF_SAIDNO
00005e42 i       *UND*                     ffffffff   DIA_WOLF_DI_HALLO_ONETIME
00005e4e i       *UND*                     ffffffff   DIA_WOLF_DI_UNDEADDRAGONDEAD_ONETIME
00005e58 i       *UND*                     ffffffff   SENTENZA_WANTS50
00005e59 i       *UND*                     ffffffff   SENTENZA_SEARCHDAY
00005e6f i       *UND*                     ffffffff   SENTENZA_GOLDGIVEN
00005e73 i       *UND*                     ffffffff   SENTENZA_EINMAL
```

Notice that all of them are integers. Daedalus scripts only ever contain global integers.

**Comment by Elgcahlxukuth** [comment]
Thanks for quick replay :)

--
> (...) unless you need to implement save-states.

Do you mean saving/loading the game state? It is likely I will need that.
What would be the best way of obtaining the list of globals that need to be taken into consideration in such scenario?

--
> (...) but none of that is instance-related (...)

by "instance" you mean:

> (...) instances (like NPCs, Items, Spells and so on) (...)

?


--

>(...) is stored within PxInstances which you have to keep track of.

I can't see `PxInstance` class/struct in any of the phoenix repositories. Could you please clarify what is meant by 'instance'?

**Comment by lmichaelis** [comment]
> What would be the best way of obtaining the list of globals that need to be taken into consideration in such scenario?

That would be to enumerate all script/vm symbols (`vm` inherits from `script`) and pick out the ones which are non-const integers. Their value can then be saved and loaded again from outside of phoenix. **This API is currently only available on the C++-side and not C-wrapper has been added yet.**

> by "instance" you mean:
> > (...) instances (like NPCs, Items, Spells and so on) (...)

Yes, most data shared between the script and the engine is represented as instances of classes. Some more documentation about that can be found in the [ModKit](https://github.com/dzieje-khorinis/Gothic-2-Mod-Development-Kit) in `documents/skripte/gothic_skripte.htm` (german). There is also limited information available on the [GMC website](https://gothic-modding-community.github.io/gmc/zengin/scripts/).

> I can't see PxInstance class/struct in any of the phoenix repositories. Could you please clarify what is meant by 'instance'?

This struct is defined in [include/phoenix/cffi/Vm.h](https://github.com/GothicKit/phoenix-shared-interface/blob/main/include/phoenix/cffi/Vm.h) of the [phoenix-shared-interface](https://github.com/GothicKit/phoenix-shared-interface) (C-library). It represents a `phoenix::instance` which can be initialized and accessed using functions defined in `Vm.h`.

**Comment by lmichaelis** [comment]
Closing this issue because this repo is now deprecated and archived. See [ZenKit4J](https://github.com/GothicKit/ZenKit4J) for the continuation of this effort.
